/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as HelpDeliveryRouteImport } from './routes/help/delivery'
import { Route as HelpOffersRouteImport } from './routes/help/offers'
import { Route as HelpPaymentRouteImport } from './routes/help/payment'
import { Route as HelpSupportRouteImport } from './routes/help/support'
import { Route as HelpTechnicalIssueRouteImport } from './routes/help/technical-issue'
import { Route as ProductsBusinessManagementRouteImport } from './routes/products/business-management'
import { Route as ProductsDomainRouteImport } from './routes/products/domain'
import { Route as ProductsHospitalManagementRouteImport } from './routes/products/hospital-management'
import { Route as ProductsHostingRouteImport } from './routes/products/hosting'
import { Route as ProductsModulexaRouteImport } from './routes/products/modulexa'
import { Route as ProductsWebTemplatesRouteImport } from './routes/products/web-templates'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin/portfolio'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin/blog/index'
import { Route as AuthenticatedAdminBlogEditorRouteImport } from './routes/_authenticated/admin/blog.editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeliveryRoute = HelpDeliveryRouteImport.update({
  id: '/help/delivery',
  path: '/help/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpOffersRoute = HelpOffersRouteImport.update({
  id: '/help/offers',
  path: '/help/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpPaymentRoute = HelpPaymentRouteImport.update({
  id: '/help/payment',
  path: '/help/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/help/support',
  path: '/help/support',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTechnicalIssueRoute = HelpTechnicalIssueRouteImport.update({
  id: '/help/technical-issue',
  path: '/help/technical-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBusinessManagementRoute =
  ProductsBusinessManagementRouteImport.update({
    id: '/products/business-management',
    path: '/products/business-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDomainRoute = ProductsDomainRouteImport.update({
  id: '/products/domain',
  path: '/products/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHospitalManagementRoute =
  ProductsHospitalManagementRouteImport.update({
    id: '/products/hospital-management',
    path: '/products/hospital-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsHostingRoute = ProductsHostingRouteImport.update({
  id: '/products/hosting',
  path: '/products/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModulexaRoute = ProductsModulexaRouteImport.update({
  id: '/products/modulexa',
  path: '/products/modulexa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWebTemplatesRoute = ProductsWebTemplatesRouteImport.update({
  id: '/products/web-templates',
  path: '/products/web-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogEditorRoute =
  AuthenticatedAdminBlogEditorRouteImport.update({
    id: '/blog/editor',
    path: '/blog/editor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$id': typeof BlogIdRoute
  '/help/delivery': typeof HelpDeliveryRoute
  '/help/offers': typeof HelpOffersRoute
  '/help/payment': typeof HelpPaymentRoute
  '/help/support': typeof HelpSupportRoute
  '/help/technical-issue': typeof HelpTechnicalIssueRoute
  '/products/business-management': typeof ProductsBusinessManagementRoute
  '/products/domain': typeof ProductsDomainRoute
  '/products/hospital-management': typeof ProductsHospitalManagementRoute
  '/products/hosting': typeof ProductsHostingRoute
  '/products/modulexa': typeof ProductsModulexaRoute
  '/products/web-templates': typeof ProductsWebTemplatesRoute
  '/services/$id': typeof ServicesIdRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/editor': typeof AuthenticatedAdminBlogEditorRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$id': typeof BlogIdRoute
  '/help/delivery': typeof HelpDeliveryRoute
  '/help/offers': typeof HelpOffersRoute
  '/help/payment': typeof HelpPaymentRoute
  '/help/support': typeof HelpSupportRoute
  '/help/technical-issue': typeof HelpTechnicalIssueRoute
  '/products/business-management': typeof ProductsBusinessManagementRoute
  '/products/domain': typeof ProductsDomainRoute
  '/products/hospital-management': typeof ProductsHospitalManagementRoute
  '/products/hosting': typeof ProductsHostingRoute
  '/products/modulexa': typeof ProductsModulexaRoute
  '/products/web-templates': typeof ProductsWebTemplatesRoute
  '/services/$id': typeof ServicesIdRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/editor': typeof AuthenticatedAdminBlogEditorRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$id': typeof BlogIdRoute
  '/help/delivery': typeof HelpDeliveryRoute
  '/help/offers': typeof HelpOffersRoute
  '/help/payment': typeof HelpPaymentRoute
  '/help/support': typeof HelpSupportRoute
  '/help/technical-issue': typeof HelpTechnicalIssueRoute
  '/products/business-management': typeof ProductsBusinessManagementRoute
  '/products/domain': typeof ProductsDomainRoute
  '/products/hospital-management': typeof ProductsHospitalManagementRoute
  '/products/hosting': typeof ProductsHostingRoute
  '/products/modulexa': typeof ProductsModulexaRoute
  '/products/web-templates': typeof ProductsWebTemplatesRoute
  '/services/$id': typeof ServicesIdRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/editor': typeof AuthenticatedAdminBlogEditorRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/license'
    | '/portfolio'
    | '/privacy'
    | '/refund'
    | '/team'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/blog/$id'
    | '/help/delivery'
    | '/help/offers'
    | '/help/payment'
    | '/help/support'
    | '/help/technical-issue'
    | '/products/business-management'
    | '/products/domain'
    | '/products/hospital-management'
    | '/products/hosting'
    | '/products/modulexa'
    | '/products/web-templates'
    | '/services/$id'
    | '/blog/'
    | '/services/'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/'
    | '/admin/blog/editor'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/license'
    | '/portfolio'
    | '/privacy'
    | '/refund'
    | '/team'
    | '/terms'
    | '/dashboard'
    | '/blog/$id'
    | '/help/delivery'
    | '/help/offers'
    | '/help/payment'
    | '/help/support'
    | '/help/technical-issue'
    | '/products/business-management'
    | '/products/domain'
    | '/products/hospital-management'
    | '/products/hosting'
    | '/products/modulexa'
    | '/products/web-templates'
    | '/services/$id'
    | '/blog'
    | '/services'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin'
    | '/admin/blog/editor'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/careers'
    | '/checkout'
    | '/contact'
    | '/license'
    | '/portfolio'
    | '/privacy'
    | '/refund'
    | '/team'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/blog/$id'
    | '/help/delivery'
    | '/help/offers'
    | '/help/payment'
    | '/help/support'
    | '/help/technical-issue'
    | '/products/business-management'
    | '/products/domain'
    | '/products/hospital-management'
    | '/products/hosting'
    | '/products/modulexa'
    | '/products/web-templates'
    | '/services/$id'
    | '/blog/'
    | '/services/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/editor'
    | '/_authenticated/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LicenseRoute: typeof LicenseRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  BlogIdRoute: typeof BlogIdRoute
  HelpDeliveryRoute: typeof HelpDeliveryRoute
  HelpOffersRoute: typeof HelpOffersRoute
  HelpPaymentRoute: typeof HelpPaymentRoute
  HelpSupportRoute: typeof HelpSupportRoute
  HelpTechnicalIssueRoute: typeof HelpTechnicalIssueRoute
  ProductsBusinessManagementRoute: typeof ProductsBusinessManagementRoute
  ProductsDomainRoute: typeof ProductsDomainRoute
  ProductsHospitalManagementRoute: typeof ProductsHospitalManagementRoute
  ProductsHostingRoute: typeof ProductsHostingRoute
  ProductsModulexaRoute: typeof ProductsModulexaRoute
  ProductsWebTemplatesRoute: typeof ProductsWebTemplatesRoute
  ServicesIdRoute: typeof ServicesIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/delivery': {
      id: '/help/delivery'
      path: '/help/delivery'
      fullPath: '/help/delivery'
      preLoaderRoute: typeof HelpDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/offers': {
      id: '/help/offers'
      path: '/help/offers'
      fullPath: '/help/offers'
      preLoaderRoute: typeof HelpOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/payment': {
      id: '/help/payment'
      path: '/help/payment'
      fullPath: '/help/payment'
      preLoaderRoute: typeof HelpPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/support': {
      id: '/help/support'
      path: '/help/support'
      fullPath: '/help/support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/technical-issue': {
      id: '/help/technical-issue'
      path: '/help/technical-issue'
      fullPath: '/help/technical-issue'
      preLoaderRoute: typeof HelpTechnicalIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/business-management': {
      id: '/products/business-management'
      path: '/products/business-management'
      fullPath: '/products/business-management'
      preLoaderRoute: typeof ProductsBusinessManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/domain': {
      id: '/products/domain'
      path: '/products/domain'
      fullPath: '/products/domain'
      preLoaderRoute: typeof ProductsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hospital-management': {
      id: '/products/hospital-management'
      path: '/products/hospital-management'
      fullPath: '/products/hospital-management'
      preLoaderRoute: typeof ProductsHospitalManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hosting': {
      id: '/products/hosting'
      path: '/products/hosting'
      fullPath: '/products/hosting'
      preLoaderRoute: typeof ProductsHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/modulexa': {
      id: '/products/modulexa'
      path: '/products/modulexa'
      fullPath: '/products/modulexa'
      preLoaderRoute: typeof ProductsModulexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/web-templates': {
      id: '/products/web-templates'
      path: '/products/web-templates'
      fullPath: '/products/web-templates'
      preLoaderRoute: typeof ProductsWebTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog/editor': {
      id: '/_authenticated/admin/blog/editor'
      path: '/blog/editor'
      fullPath: '/admin/blog/editor'
      preLoaderRoute: typeof AuthenticatedAdminBlogEditorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogEditorRoute: typeof AuthenticatedAdminBlogEditorRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPortfolioRoute: AuthenticatedAdminPortfolioRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminBlogEditorRoute: AuthenticatedAdminBlogEditorRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LicenseRoute: LicenseRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  BlogIdRoute: BlogIdRoute,
  HelpDeliveryRoute: HelpDeliveryRoute,
  HelpOffersRoute: HelpOffersRoute,
  HelpPaymentRoute: HelpPaymentRoute,
  HelpSupportRoute: HelpSupportRoute,
  HelpTechnicalIssueRoute: HelpTechnicalIssueRoute,
  ProductsBusinessManagementRoute: ProductsBusinessManagementRoute,
  ProductsDomainRoute: ProductsDomainRoute,
  ProductsHospitalManagementRoute: ProductsHospitalManagementRoute,
  ProductsHostingRoute: ProductsHostingRoute,
  ProductsModulexaRoute: ProductsModulexaRoute,
  ProductsWebTemplatesRoute: ProductsWebTemplatesRoute,
  ServicesIdRoute: ServicesIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
